
  create table "public"."alquiler" (
    "id_alquiler" bigint generated by default as identity not null,
    "nombre_evento" character varying not null,
    "fecha" date not null,
    "hora" time without time zone not null,
    "user_id" bigint not null
      );


alter table "public"."pelicula" add column "idioma" character varying not null;

alter table "public"."pelicula" alter column "id_pelicula" set generated by default;

CREATE UNIQUE INDEX alquiler_pkey ON public.alquiler USING btree (id_alquiler);

alter table "public"."alquiler" add constraint "alquiler_pkey" PRIMARY KEY using index "alquiler_pkey";

alter table "public"."alquiler" add constraint "alquiler_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."user"(id) not valid;

alter table "public"."alquiler" validate constraint "alquiler_user_id_fkey";

grant delete on table "public"."alquiler" to "anon";

grant insert on table "public"."alquiler" to "anon";

grant references on table "public"."alquiler" to "anon";

grant select on table "public"."alquiler" to "anon";

grant trigger on table "public"."alquiler" to "anon";

grant truncate on table "public"."alquiler" to "anon";

grant update on table "public"."alquiler" to "anon";

grant delete on table "public"."alquiler" to "authenticated";

grant insert on table "public"."alquiler" to "authenticated";

grant references on table "public"."alquiler" to "authenticated";

grant select on table "public"."alquiler" to "authenticated";

grant trigger on table "public"."alquiler" to "authenticated";

grant truncate on table "public"."alquiler" to "authenticated";

grant update on table "public"."alquiler" to "authenticated";

grant delete on table "public"."alquiler" to "service_role";

grant insert on table "public"."alquiler" to "service_role";

grant references on table "public"."alquiler" to "service_role";

grant select on table "public"."alquiler" to "service_role";

grant trigger on table "public"."alquiler" to "service_role";

grant truncate on table "public"."alquiler" to "service_role";

grant update on table "public"."alquiler" to "service_role";


